---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Getting started: Webhook Example"
      solveButton: false
    - name: module-02
      label: "Getting started: Kafka Example"
      solveButton: false
    - name: module-03
      label: "Getting started: URL Check Example"
      solveButton: false

tabs:
  - name: ">_ ansible_rulebook"
    url: /wetty_webserver
    secondary_name: ">_ terminal"
    secondary_url: /wetty_webserver
  - name: ">_ kafka"
    url: /wetty_broker

  # - name: Cloud (PoC)
  #   url: /cloud
